{% set name = "mixsea" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8f4b83886ef15b3ec9e321e99c95ce5440081e11fa71c0fa29a2f05a83020635

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.8.22,<0.9.0
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2
    - scipy >=1.6.0
    - gsw >=3.6

test:
  imports:
    - mixsea
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/modscripps/mixsea
  summary: Ocean mixing parameterizations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
